#Take Reference from here https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml

theme: jekyll-theme-cayman

#Title of Webpage
title: Cracking the Coding Interview

#Short Description of Webpage
description: Diving into Data Structures and Algorithms

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "https://www.utdallas.edu/~txg170003/"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"


# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "someone@example.com"
  facebook: daattali
  github: daattali
  twitter: daattali
#  reddit: yourname
  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
